<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Profession;

class ProfessionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $professions = [
    // Salud
    ['category' => 'Salud', 'name' => 'Acupunturista'],
    ['category' => 'Salud', 'name' => 'Cardíologo'],
    ['category' => 'Salud', 'name' => 'Cirujano'],
    ['category' => 'Salud', 'name' => 'Dentista'],
    ['category' => 'Salud', 'name' => 'Dermatólogo'],
    ['category' => 'Salud', 'name' => 'Dietista'],
    ['category' => 'Salud', 'name' => 'Endocrinólogo'],
    ['category' => 'Salud', 'name' => 'Endodoncista'],
    ['category' => 'Salud', 'name' => 'Fisioterapeuta'],
    ['category' => 'Salud', 'name' => 'Fonoaudiólogo'],
    ['category' => 'Salud', 'name' => 'Gastroenterólogo'],
    ['category' => 'Salud', 'name' => 'Ginecólogo'],
    ['category' => 'Salud', 'name' => 'Herbolario'],
    ['category' => 'Salud', 'name' => 'Homeópata'],
    ['category' => 'Salud', 'name' => 'Kinesiologo'],
    ['category' => 'Salud', 'name' => 'Médico especialista'],
    ['category' => 'Salud', 'name' => 'Médico General'],
    ['category' => 'Salud', 'name' => 'Médico veterinario'],
    ['category' => 'Salud', 'name' => 'Neumólogo'],
    ['category' => 'Salud', 'name' => 'Neurólogo'],
    ['category' => 'Salud', 'name' => 'Nutricionista'],
    ['category' => 'Salud', 'name' => 'Oftalmólogo'],
    ['category' => 'Salud', 'name' => 'Oncólogo'],
    ['category' => 'Salud', 'name' => 'Ortodoncista'],
    ['category' => 'Salud', 'name' => 'Osteópata'],
    ['category' => 'Salud', 'name' => 'Otorrinolaringólogo'],
    ['category' => 'Salud', 'name' => 'Pediatra'],
    ['category' => 'Salud', 'name' => 'Periodoncista'],
    ['category' => 'Salud', 'name' => 'Podólogo'],
    ['category' => 'Salud', 'name' => 'Psicólogo'],
    ['category' => 'Salud', 'name' => 'Psicopedagogo'],
    ['category' => 'Salud', 'name' => 'Psiquiatra'],
    ['category' => 'Salud', 'name' => 'Quiropráctico'],
    ['category' => 'Salud', 'name' => 'Terapista ocupacional'],
    ['category' => 'Salud', 'name' => 'Terapeuta alternativo'],
    ['category' => 'Salud', 'name' => 'Traumatólogo'],
    ['category' => 'Salud', 'name' => 'Urólogo'],
    ['category' => 'Salud', 'name' => 'Veterinario especialista'],
    ['category' => 'Salud', 'name' => 'Zootecnista'],

    // Estética y Bienestar
    ['category' => 'Estética y Bienestar', 'name' => 'Asesor de imagen'],
    ['category' => 'Estética y Bienestar', 'name' => 'Barbero'],
    ['category' => 'Estética y Bienestar', 'name' => 'Coach de belleza'],
    ['category' => 'Estética y Bienestar', 'name' => 'Cosmetóloga'],
    ['category' => 'Estética y Bienestar', 'name' => 'Depilación laser'],
    ['category' => 'Estética y Bienestar', 'name' => 'Entrenador personal'],
    ['category' => 'Estética y Bienestar', 'name' => 'Esteticista'],
    ['category' => 'Estética y Bienestar', 'name' => 'Estilista de cejas'],
    ['category' => 'Estética y Bienestar', 'name' => 'Extensiones de pestañas'],
    ['category' => 'Estética y Bienestar', 'name' => 'Instructor de pilates'],
    ['category' => 'Estética y Bienestar', 'name' => 'Instructor de yoga'],
    ['category' => 'Estética y Bienestar', 'name' => 'Lifting de pestañas'],
    ['category' => 'Estética y Bienestar', 'name' => 'Manicurista'],
    ['category' => 'Estética y Bienestar', 'name' => 'Maquillador'],
    ['category' => 'Estética y Bienestar', 'name' => 'Masajista'],
    ['category' => 'Estética y Bienestar', 'name' => 'Microblading'],
    ['category' => 'Estética y Bienestar', 'name' => 'Micropigmentación'],
    ['category' => 'Estética y Bienestar', 'name' => 'Nutricionista deportivo'],
    ['category' => 'Estética y Bienestar', 'name' => 'Pedicurista'],
    ['category' => 'Estética y Bienestar', 'name' => 'Peluquero'],
    ['category' => 'Estética y Bienestar', 'name' => 'Piercer'],
    ['category' => 'Estética y Bienestar', 'name' => 'Quiromasajista'],
    ['category' => 'Estética y Bienestar', 'name' => 'Reflexólogo'],
    ['category' => 'Estética y Bienestar', 'name' => 'Tatuador'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de aromaterapia'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de calor'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de drenaje linfático'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de frío'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de hidroterapia'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de luz LED'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de masaje deportivo'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de masaje relajante'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de masaje terapéutico'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de ozono'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de quiromasaje'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de reflexología podal'],
    ['category' => 'Estética y Bienestar', 'name' => 'Terapeuta de spa'],
    ['category' => 'Estética y Bienestar', 'name' => 'Tratamientos corporales'],
    ['category' => 'Estética y Bienestar', 'name' => 'Tratamientos faciales'],

    // Servicios profesionales
    ['category' => 'Servicios profesionales', 'name' => 'Abogado'],
    ['category' => 'Servicios profesionales', 'name' => 'Adiestrador de mascotas'],
    ['category' => 'Servicios profesionales', 'name' => 'Arquitecto'],
    ['category' => 'Servicios profesionales', 'name' => 'Asesor de comercio exterior'],
    ['category' => 'Servicios profesionales', 'name' => 'Asesor de inversiones'],
    ['category' => 'Servicios profesionales', 'name' => 'Asesor de propiedad inmobiliaria'],
    ['category' => 'Servicios profesionales', 'name' => 'Asesor de seguros'],
    ['category' => 'Servicios profesionales', 'name' => 'Asesor fiscal'],
    ['category' => 'Servicios profesionales', 'name' => 'Asesor legal'],
    ['category' => 'Servicios profesionales', 'name' => 'Coach de carrera'],
    ['category' => 'Servicios profesionales', 'name' => 'Coach de fitness'],
    ['category' => 'Servicios profesionales', 'name' => 'Coach de nutrición'],
    ['category' => 'Servicios profesionales', 'name' => 'Coach de relaciones'],
    ['category' => 'Servicios profesionales', 'name' => 'Coach de salud'],
    ['category' => 'Servicios profesionales', 'name' => 'Coach de vida'],
    ['category' => 'Servicios profesionales', 'name' => 'Coach ejecutivo'],
    ['category' => 'Servicios profesionales', 'name' => 'Coach personal'],
    ['category' => 'Servicios profesionales', 'name' => 'Community manager'],
    ['category' => 'Servicios profesionales', 'name' => 'Consultor de IT'],
    ['category' => 'Servicios profesionales', 'name' => 'Consultor de marketing'],
    ['category' => 'Servicios profesionales', 'name' => 'Consultor de negocios'],
    ['category' => 'Servicios profesionales', 'name' => 'Consultor de recursos humanos'],
    ['category' => 'Servicios profesionales', 'name' => 'Consultor financiero'],
    ['category' => 'Servicios profesionales', 'name' => 'Contador'],
    ['category' => 'Servicios profesionales', 'name' => 'Diseñador gráfico'],
    ['category' => 'Servicios profesionales', 'name' => 'Fotografo'],
    ['category' => 'Servicios profesionales', 'name' => 'Fotógrafo de mascotas'],
    ['category' => 'Servicios profesionales', 'name' => 'Ingeniero civil'],
    ['category' => 'Servicios profesionales', 'name' => 'Organizador de bodas'],
    ['category' => 'Servicios profesionales', 'name' => 'Peluquero de mascotas'],
    ['category' => 'Servicios profesionales', 'name' => 'Productor de eventos'],
    ['category' => 'Servicios profesionales', 'name' => 'Videógrafo'],

    // Servicios Técnicos
    ['category' => 'Servicios Técnicos', 'name' => 'Carpintero'],
    ['category' => 'Servicios Técnicos', 'name' => 'Cerrajero'],
    ['category' => 'Servicios Técnicos', 'name' => 'Control de plagas'],
    ['category' => 'Servicios Técnicos', 'name' => 'Electricista'],
    ['category' => 'Servicios Técnicos', 'name' => 'Jardinero'],
    ['category' => 'Servicios Técnicos', 'name' => 'Mecánico'],
    ['category' => 'Servicios Técnicos', 'name' => 'Paisajista'],
    ['category' => 'Servicios Técnicos', 'name' => 'Pintor'],
    ['category' => 'Servicios Técnicos', 'name' => 'Plomero'],
    ['category' => 'Servicios Técnicos', 'name' => 'Poda de árboles'],
    ['category' => 'Servicios Técnicos', 'name' => 'Servicio de limpieza'],
    ['category' => 'Servicios Técnicos', 'name' => 'Servicio de mantenimiento general'],
    ['category' => 'Servicios Técnicos', 'name' => 'Servicio de mudanzas'],
    ['category' => 'Servicios Técnicos', 'name' => 'Tapicero'],
    ['category' => 'Servicios Técnicos', 'name' => 'Técnico de aire acondicionado'],
    ['category' => 'Servicios Técnicos', 'name' => 'Técnico de computadoras'],
    ['category' => 'Servicios Técnicos', 'name' => 'Técnico de electrodomésticos'],
    ['category' => 'Servicios Técnicos', 'name' => 'Técnico de redes'],
    ['category' => 'Servicios Técnicos', 'name' => 'Técnico de refrigeración'],
    ['category' => 'Servicios Técnicos', 'name' => 'Técnico de seguridad electrónica'],
    ['category' => 'Servicios Técnicos', 'name' => 'Técnico de sistemas de alarma'],
    ['category' => 'Servicios Técnicos', 'name' => 'Técnico de telefonía móvil'],

    // Otros
    ['category' => 'Otros', 'name' => 'Artista'],
    ['category' => 'Otros', 'name' => 'Dueño de negocio'],
    ['category' => 'Otros', 'name' => 'Emprendedor'],
    ['category' => 'Otros', 'name' => 'Escritor'],
    ['category' => 'Otros', 'name' => 'Freelance'],
    ['category' => 'Otros', 'name' => 'Músico'],
    ['category' => 'Otros', 'name' => 'Otro'],
];

        foreach ($professions as $profession) {
            Profession::create($profession);
        }
    }
}
